export const promptQuestions: string[] = [
  "A life goal of mine",
  "I'm convinced that",
  "We're the same type of weird if",
  "My perfect Sunday",
  "My simple pleasures",
  "I'll know it's real when",
  "A fact about me that surprises people",
  "Together we could",
  "I'm looking for",
  "My most controversial opinion",
  "Unusual skills",
  "The way to my heart",
  "My biggest green flag",
  "I geek out on",
  "My love language is",
  "The key to my heart is",
  "A boundary I have is",
  "I feel most alive when",
  "My dream dinner guest",
  "If I could live anywhere",
  "I'm most proud of",
  "The best gift I ever received",
  "My guilty pleasure",
  "Something I'll never do again",
];
